name: CI with code coverage support

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Java setup
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests with coverage
        run: mvn clean verify

      - name: Upload coverage data to Coveralls
        uses: coverallsapp/github-action@v2
